- {component_type: servo, description: greenhouse window, id: 7, kind: actuator, name: window,
  pin: '7', uid: 4602b88a}
- {component_type: pump, description: irrigation pump, id: 8, kind: actuator, name: pump,
  pin: '8', uid: 8b9b50c3}
