- {component_type: servo, description: greenhouse window, id: 7, kind: actuator, name: window,
  pin: '7', uid: e09df193}
- {component_type: pump, description: irrigation pump, id: 8, kind: actuator, name: pump,
  pin: '8', uid: 998838ac}
