profiles:
  local:
  test:
  remote:
default:
manager:
# url: 192.168.0.13
  url: 10.0.88.108
  port: 8888
  get_config_endpoints:
    nodule: nodule/{n_id}/nodule
    hardware: nodule/{n_id}/hardware
    sensors: nodule/{n_id}/sensors
    actuators: nodule/{n_id}/actuators
    jobs: nodule/{n_id}/jobs
mqtt:
  mqtt_url: 10.0.88.108
  mqtt_port: 1883
  mqtt_keepalive: 1883


topics: [sensors, logs, errors, report, presence]
valid_pins:
  raspi: [0,1,2,3,4,5,6,7,8,"cpu_temp","du"]
  esp8266: [0,1,2,3,4, 90,91,92,93,94]
  local: [0,1,2,3]
