- {component: 55d366f4, description: Turns on lamp in living room, id: 10, interval: 100,
  kind: actuator, name: room lamp, start_day: '', tags: _, uid: 37bef1a5, units: ''}
- {component: fdba470c, description: Light intensity in living rom, id: 9, interval: 30,
  kind: sensor, name: room light, start_day: '', tags: _, uid: 7f460e4f, units: ''}
- {component: '18906459', description: Moisture of soil in chive pot, id: 8, interval: 17,
  kind: sensor, name: chive_moist, start_day: '', tags: _, uid: 6ac41cdd, units: ''}
