- {component: 64b2c2ed, description: Turns on lamp in living room, id: 10, interval: 100,
  kind: actuator, name: room lamp, start_day: '', tags: _, uid: 2f306976, units: ''}
- {component: 49bcabfd, description: Light intensity in living rom, id: 9, interval: 30,
  kind: sensor, name: room light, start_day: '', tags: _, uid: 4047bdee, units: ''}
- {component: 6d6d539c, description: Moisture of soil in chive pot, id: 8, interval: 17,
  kind: sensor, name: chive_moist, start_day: '', tags: _, uid: 1393bd87, units: ''}
