- {component: 6a0b3839, description: ds18b20, id: 9, interval: 10, kind: sensor, name: ds18b20,
  start_day: '', tags: _, uid: be9452fa, units: ''}
- {component: de90bb9f, description: Runs the pump, id: 7, interval: 25, kind: actuator,
  name: run pump, start_day: '', tags: _, uid: 3c661f42, units: ''}
- {component: da682dc1, description: Light intensity on balcony, id: 6, interval: 5,
  kind: sensor, name: balcony light, start_day: '', tags: _, uid: 1e83da57, units: lux}
- {component: b7f7d6c4, description: Moisture of soil in aubergine pot, id: 5, interval: 20,
  kind: sensor, name: aubergine soil moisture, start_day: '', tags: _, uid: c5f18cc9,
  units: '%'}
- {component: 8ebf2dd5, description: Moisture of soil in tomato pot, id: 4, interval: 20,
  kind: sensor, name: tomato soil moisture, start_day: '', tags: _, uid: 1984cc12,
  units: '%'}
- {component: 4d2e9ebf, description: Temperature of soil in aubergine pot, id: 3,
  interval: 20, kind: sensor, name: aubergine soil temp, start_day: '', tags: _, uid: 4dbe5269,
  units: C}
- {component: b416457d, description: Temperature of soil in tomato pot, id: 2, interval: 20,
  kind: sensor, name: tomato soil temp, start_day: '', tags: _, uid: 7cc5c332, units: C}
- {component: 91b7eef4, description: Balcony air temperature and humidity, id: 1,
  interval: 5, kind: sensor, name: balcony air temp, start_day: '', tags: _, uid: 2a7eea38,
  units: C/%}
