- {component: eed60a27, description: Runs the pump, id: 7, interval: 25, kind: actuator,
  name: run pump, start_day: '', tags: _, uid: f8c3a2ec, units: ''}
- {component: affbfc89, description: Light intensity on balcony, id: 6, interval: 5,
  kind: sensor, name: balcony light, start_day: '', tags: _, uid: 204d5f8c, units: lux}
- {component: 42858ee8, description: Moisture of soil in aubergine pot, id: 5, interval: 20,
  kind: sensor, name: aubergine soil moisture, start_day: '', tags: _, uid: b3e6864f,
  units: '%'}
- {component: 71d59404, description: Moisture of soil in tomato pot, id: 4, interval: 20,
  kind: sensor, name: tomato soil moisture, start_day: '', tags: _, uid: d2821188,
  units: '%'}
- {component: 076ba3e1, description: Temperature of soil in aubergine pot, id: 3,
  interval: 20, kind: sensor, name: aubergine soil temp, start_day: '', tags: _, uid: 3bf977b1,
  units: C}
- {component: '97771921', description: Temperature of soil in tomato pot, id: 2, interval: 20,
  kind: sensor, name: tomato soil temp, start_day: '', tags: _, uid: c7af8bd4, units: C}
- {component: 02c1c6a7, description: Balcony air temperature and humidity, id: 1,
  interval: 5, kind: sensor, name: balcony air temp, start_day: '', tags: _, uid: 9c003b95,
  units: C/%}
