UID: ABC123
# node_name: Foo
debug: true

err_log_size: 150
log_size: 500
topics: [sensors, logs, errors, report, presence]
batch: False  # Publish continuously, or batch messages

# HW_TYPE: local
HW_TYPE: esp8266
# HW_TYPE: esp32
# HW_TYPE: rpi
