- {component_type: DHT_11, description: balcony temperature/humidity, id: 1, kind: sensor,
  name: balc temp/hmdy, pin: '1', uid: '03036137'}
- {component_type: ds18b20, description: tomato soil temp, id: 2, kind: sensor, name: tom_soil_temp,
  pin: i2c_2, uid: ca80129c}
- {component_type: ds18b20, description: aubergine soil temp, id: 3, kind: sensor,
  name: aub_soil_temp, pin: i2c_3, uid: 73a3c048}
- {component_type: moisture, description: tomato soil moisture, id: 4, kind: sensor,
  name: tom_soil_moist, pin: '4', uid: 3049f745}
- {component_type: moisture, description: aubergine soil moisture, id: 5, kind: sensor,
  name: aub_soil_moist, pin: '5', uid: 7f05b66d}
- {component_type: TSL2561, description: balcony light intensity, id: 6, kind: sensor,
  name: balc lux, pin: i2c_6, uid: ee14b8fa}
- {component_type: ds18b20, description: tomato soil temp, id: 13, kind: sensor, name: test_quick,
  pin: i2c_2, uid: 9a31de00}
