- {component_type: DHT_11, description: balcony temperature/humidity, id: 1, kind: sensor,
  name: balc temp/hmdy, pin: '1', uid: 02c1c6a7}
- {component_type: ds18b20, description: tomato soil temp, id: 2, kind: sensor, name: tom_soil_temp,
  pin: i2c_2, uid: '97771921'}
- {component_type: ds18b20, description: aubergine soil temp, id: 3, kind: sensor,
  name: aub_soil_temp, pin: i2c_3, uid: 076ba3e1}
- {component_type: moisture, description: tomato soil moisture, id: 4, kind: sensor,
  name: tom_soil_moist, pin: '4', uid: 71d59404}
- {component_type: moisture, description: aubergine soil moisture, id: 5, kind: sensor,
  name: aub_soil_moist, pin: '5', uid: 42858ee8}
- {component_type: TSL2561, description: balcony light intensity, id: 6, kind: sensor,
  name: balc lux, pin: i2c_6, uid: affbfc89}
