- {component_type: moisture, description: chive soil moisture, id: 9, kind: sensor,
  name: chive_soil_moist, pin: '1', uid: 6d6d539c}
- {component_type: TSL2561, description: living room light intensity, id: 10, kind: sensor,
  name: room lux, pin: i2c_2, uid: 49bcabfd}
