- {component_type: DHT_11, description: balcony temperature/humidity, id: 1, kind: sensor,
  name: balc temp/hmdy, pin: '1', uid: e83dc99c}
- {component_type: ds18b20, description: tomato soil temp, id: 2, kind: sensor, name: tom_soil_temp,
  pin: i2c_2, uid: 8397e6b5}
- {component_type: ds18b20, description: aubergine soil temp, id: 3, kind: sensor,
  name: aub_soil_temp, pin: i2c_3, uid: e51f5751}
- {component_type: moisture, description: tomato soil moisture, id: 4, kind: sensor,
  name: tom_soil_moist, pin: '4', uid: c4f59959}
- {component_type: moisture, description: aubergine soil moisture, id: 5, kind: sensor,
  name: aub_soil_moist, pin: '5', uid: 4e7d50e2}
- {component_type: TSL2561, description: balcony light intensity, id: 6, kind: sensor,
  name: balc lux, pin: i2c_6, uid: 5da99a51}
- {component_type: ds18b20, description: ds18b20, id: 12, kind: sensor, name: ds18b20,
  pin: '4', uid: f837e66a}
